language: python
sudo: false
cache: pip
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
    - PYPI_USER_NAME: chaostoolkit
    - secure: "apf1ro4EZhRpiW1OHJ6lFm9HCtQjMOsrhrmVivN+XvPJjBa+mYTZNFaS+K4s0VFSMn/MzGWZEf9nPIlDRyx9L97wW/nk6d1slDXRGIvxFEnkd3eDONTk0n7DcokbsauKizsscniU6uuvjZmLxyEFTQTkYnxmMUPhY8gsvsVTkmDG2TPkZqaTDVpSkzpRyxiv0cNhkn9f0U2StE5alxFkkErTtINLvENyZvGVKKHtuLorv32U5rtoVBr7JhruQ53NhVsqwDlnCUgREx+6qyf8pNqDy8aXHkTwpQenSxycBY2KEjLdf2DTQmNziex9tndDxuFlR5qaGggA1In53rlyCcH5JQBRWgkjuHLE5sLKpCBg1iYeG44P+TIxHj2r5Rpmm2AjUZsD/Fa+iu8akJAi/ZYIdqbwInna3H0Hgns6xpJuFg8XQR96kjsTc4E7qxepj2NgkRvFZRGJPayCbuZqfp88BCG3Bu7sm4bllylIgMT4viWXBtE4dblqz0AmTKN5v3EMlIeqO/GD/YnQb9H7OkApvbtpBiLcX5l0IwOqHRCYiiUqknGaAZGCKcLQyvaKUB9lJRRVRpJKvDayYUjcdPtiBs3doazbq6EBz1qsVvssl/5Uv2RreVEt+ag9EEIm53jPqg6FBZsUHp0Rhy1L9rEDIhNHE8VwuTH+HGn7yoM="
python:
  - "3.6"
  - "3.7-dev"
install:
  - virtualenv --version
  - pip install -U pip setuptools
  - pip --version
  - pip install --pre -r requirements.txt -r requirements-dev.txt
script:
  - bash ci.bash
notifications:
  webhooks:
    urls:
    - "https://webhook.atomist.com/atomist/travis/teams/T76U4GPGF"
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always
