[chaosplatform]
debug = false

    [chaosplatform.grpc]
    address = "0.0.0.0:50051"

    [chaosplatform.http]
    address = "0.0.0.0:8090"
    secret_key = ""

        [chaosplatform.http.cherrypy]
        environment = "production"
        proxy = "http://localhost:6080"

    [chaosplatform.cache]
    type = "simple"

        # Only set if type is set to "redis"
        # [chaosplatform.cache.redis]
        # host = "localhost"
        # port = 6379

    [chaosplatform.db]
    uri = "sqlite:///:memory"

    [chaosplatform.jwt]
    secret_key = ""
    public_key = ""
    algorithm = "HS256"
    identity_claim_key = "identity"
    user_claims_key = "user_claims"
    access_token_expires = 2592000
    refresh_token_expires = 31536000
    user_claims_in_refresh_token = false

    [chaosplatform.account]

    [chaosplatform.auth]
        [chaosplatform.auth.oauth2]
            [chaosplatform.auth.oauth2.github]
            client_id = ""
            client_secret = ""

        [chaosplatform.auth.grpc]
            [chaosplatform.auth.grpc.account]
            address = "0.0.0.0:50051"

    [chaosplatform.experiment]

    [chaosplatform.scheduling]
        [chaosplatform.scheduling.grpc]
            [chaosplatform.scheduling.grpc.scheduler]
            address = "0.0.0.0:50051"

    [chaosplatform.scheduler]
        [chaosplatform.scheduler.redis]
        host = "localhost"
        port = 6379
        queue = "chaosplatform"

        [chaosplatform.scheduler.job]
        platform_url = "http://127.0.0.1:6080"

        [chaosplatform.scheduler.worker]
        debug = false
        count = 3
        queue_name = "chaosplatform"
        worker_name = "chaosplatform-worker"
        add_random_suffix_to_worker_name = true
        worker_directory = "/tmp"

        [chaosplatform.scheduler.worker.redis]
        host = "localhost"
        port = 6379